"""PDF generation for research reports."""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer


def generate_research_pdf(
    query: str,
    goal: str,
    final_output: str,
    created_at: str | None = None,
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    
    story = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a1a"),
        spaceAfter=12,
        alignment=1,
    )
    
    subtitle_style = ParagraphStyle(
        "CustomSubtitle",
        parent=styles["Normal"],
        fontSize=12,
        textColor=colors.HexColor("#666666"),
        spaceAfter=20,
        alignment=1,
    )
    
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=16,
        textColor=colors.HexColor("#2c3e50"),
        spaceAfter=12,
        spaceBefore=12,
    )
    
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#333333"),
        leading=16,
        spaceAfter=12,
    )
    
    story.append(Paragraph("Research Report", title_style))
    story.append(Paragraph(f"Generated by AgentOffice", subtitle_style))
    
    if created_at:
        date_str = datetime.fromisoformat(created_at).strftime("%B %d, %Y at %I:%M %p")
    else:
        date_str = datetime.utcnow().strftime("%B %d, %Y at %I:%M %p")
    story.append(Paragraph(f"Created: {date_str}", subtitle_style))
    
    story.append(Spacer(1, 0.3 * inch))
    
    story.append(Paragraph("Research Query", heading_style))
    story.append(Paragraph(query, body_style))
    story.append(Spacer(1, 0.2 * inch))
    
    story.append(Paragraph("Research Goal", heading_style))
    story.append(Paragraph(goal, body_style))
    story.append(Spacer(1, 0.3 * inch))
    
    story.append(PageBreak())
    
    story.append(Paragraph("Research Findings", heading_style))
    story.append(Spacer(1, 0.1 * inch))
    
    for line in final_output.split("\n"):
        if line.strip():
            if line.startswith("##"):
                cleaned = line.replace("##", "").strip()
                story.append(Paragraph(cleaned, heading_style))
            elif line.startswith("###"):
                cleaned = line.replace("###", "").strip()
                sub_heading_style = ParagraphStyle(
                    "SubHeading",
                    parent=heading_style,
                    fontSize=14,
                )
                story.append(Paragraph(cleaned, sub_heading_style))
            else:
                story.append(Paragraph(line, body_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer.read()
